[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["--cov=rt_stoppers_contrib", "-ra", "--showlocals", "--strict-markers", "--strict-config", "--cov-branch"]
xfail_strict = true
testpaths = [
  "test",
]

[tool.pycln]
all = true
